### ISSUE TITLE
Bootstrap changes

### ISSUE THREAD

**Issue by fredrkr** [CreITive/Laravel-4-Breadcrumbs#9]
http://getbootstrap.com/components/#breadcrumbs
As indicated in the URL above, Bootstrap now uses an ol-element with the class "breadcrumb" (singular) for the breadcrumbs-component. As far as I can tell, there are no config-options for changing the containing html tag in this package.

Do you plan on updating the package so that it is once again Bootstrap-compatible?

Thanks!

**Comment by levacic** [comment]
Hey, thanks for the notice, and sure, we can update it - although a better approach would probably be to split the rendering logic into a customizable view, so that the user can configure their own view for rendering the breadcrumbs, in case we don't natively support their front-end framework of choice (as it is now, the rendering logic is pretty much hard-coded into the class, which certainly isn't a good solution).

This is a bit more work, since we'll also need to update tests (off the top of my head, [this one](https://github.com/CreITive/Laravel-4-Breadcrumbs/blob/master/tests/BreadcrumbsTest.php#L244-L273) will surely need changing], but I'll have some time over the weekend and I can give it a go.

Of course, if you want, feel free to send a PR, and we'll gladly accept it!

Cheers.

**Comment by fredrkr** [comment]
I completely agree with the view-logic separation argument. As you say however, *that* takes a little more doing. 

I've seen many Laravel-packages that lets you "publish" certain things using artisan. Breadcrumbs could use a default view, which is overridden by user-published views, for instance.

I'd love to help out, but I don't have any experience with tests. I could submit a PR that makes the package compatible with the current version of Bootstrap, if you'd like though.

**Comment by levacic** [comment]
If we just change the `<ul>` to `<ol>`, that would break compatibility for current users.

We need to give this a bit more thought, since converting to a view-based system is better, but that would be another BC-break, since it would couple this library to Laravel (and although that was the primary idea in the first place, some people might use it independently, and we don't want to break their code).

For now though, we'll likely stick to hard-coded rendering, but with a configurable option for the containing element.

At some point, when we decide on a version 2 release, we'll likely go to a view-based mechanism, coupling the package to Laravel, and maintain version 1 for non-Laravel users.

**Comment by fredrkr** [comment]
To make it compatible with current builds of Bootstrap, a configurable container-element is all you need, really.

Kudos for quick responses. Thanks!

**Comment by fredrkr** [comment]
Okay, so I added a setListElement-method #10 so that one can set the list element to whatever. It's set to ul by default, so it shouldn't break compatibility, like you mentioned.

**Comment by levacic** [comment]
Closed via #10 

Sorry for taking a bit to get to this, and thanks for the PR!
